#!/usr/bin/env bash

usage() {
  echo "Usage: $0 [speed=2|2.5|4|5|10|20|50] <input> [output]" >&2
  exit 1
}

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  usage
fi

speedup="${1%x}"
shift
input="$1"
shift
if [ $# -gt 0 ]; then
  output="$1"
  shift
else
  base="${input%.*}"
  extension="${input##*.}"
  output="${base}-${speedup}x.${extension}"
fi

num_audio_streams="$(ffprobe -v error -select_streams a -show_entries stream=index -of csv=p=0 "$input" | wc -w)"

case "$speedup" in
  2)
    setpts=0.5
    atempo="atempo=2.0"
    ;;
  2.5)
    setpts=0.4
    atempo="atempo=2.0,atempo=1.25"
    ;;
  4)
    setpts=0.25
    atempo="atempo=2.0,atempo=2.0"
    ;;
  5)
    setpts=0.2
    atempo="atempo=2.0,atempo=2.0,atempo=1.25"
    ;;
  10)
    setpts=0.1
    atempo="atempo=2.0,atempo=2.0,atempo=2.0,atempo=1.25"
    ;;
  20)
    setpts=0.05
    atempo="atempo=2.0,atempo=2.0,atempo=2.0,atempo=2.0,atempo=1.25"
    ;;
  50)
    setpts=0.1
    atempo="atempo=2.0,atempo=2.0,atempo=2.0,atempo=1.25"
    ;;
  *)
    usage
    ;;
esac

echo "$input $setpts $atempo $output"

filter="[0:v]setpts=$setpts*PTS[v]"
map_args=(-map "[v]")
if [ "$num_audio_streams" -gt 0 ]; then
  filter+="[0:a]${atempo}[a]"
  map_args+=(-map "[a]")
fi
ffmpeg -i "$input" -filter_complex "$filter" "${map_args[@]}" "$output"
