#!/usr/bin/env bash

# Pad an image on its smaller dimension with transparent pixels until it is square
# Taken from https://stackoverflow.com/a/34998291

in="$1"; shift
if [ $# -gt 0 ]; then
  out="$1"; shift
else
  out="${in%.*}-padded.${in##*.}"
fi

# Observed this method to take an existingi 650x650 image and make it 925x1200 for some reason
# convert "$in" \( +clone -rotate 90 +clone -mosaic +level-colors grey -transparent grey \) +swap -gravity center -composite "$out"

convert "$in" \
  +set date:create +set date:modify \
  -virtual-pixel none \
  -set option:distort:viewport \
  "%[fx:max(w,h)]x%[fx:max(w,h)]-%[fx:max((h-w)/2,0)]-%[fx:max((w-h)/2,0)]" \
  -filter point \
  -distort SRT 0 \
  +repage \
  "$out"


