#!/usr/bin/env bash

set -e

if [ $# -eq 0 ]; then
  "$0" .
else
  for arg in "$@"; do
    if [ -d "$arg" ]; then
      find "$arg" -name '*.tiff' | parallel -k -j+0 --env PATH "$0"
    else
      name="${arg%.tiff}"
      if [ "$name" == "$arg" ]; then
        echo "Not a tiff; skipping $arg" >&2
      else
        out="$name.png"
        if [ -s "$out" ]; then
          echo "Found $out; skipping" >&2
        else
          echo "Converting: $arg → $out" >&2
          magick "$arg" "$out"
          if [ -e "$out" ]; then
            rm -f "$arg"
          else
            echo "Conversion failed? $out not found" >&2
          fi
        fi
      fi
    fi
  done
fi
