#!/usr/bin/env bash

set -e

if [ $# -eq 0 ]; then
  "$0" .
else
  for arg in "$@"; do
    if [ -d "$arg" ]; then
      find "$arg" -name '*.tiff' | parallel -k -j+0 --env PATH "$0"
    else
      name="${arg%.tiff}"
      if [ "$name" == "$arg" ]; then
        echo "Not a tiff; skipping $arg" >&2
      else
        out="$name.png"
        if [ -s "$out" ]; then
          echo "Found $out; skipping"
        else
          echo "Converting: $arg → $out"
          convert "$arg" "$out"
          rm -f "$arg"
        fi
      fi
    fi
  done
fi
